dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  # update npm to allow use of 'npm ci'
  - npm install -g npm@latest
  - npm ci

script:
  - npm run test -- --watch=false --progress=false --browsers=myChromeHeadless
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

